### ISSUE TITLE
Error when implementing own Atlasttk server

### ISSUE THREAD

**Issue by bkcallihan** [epeios-q37/xdhq#1]
I have been struggling with implementing the instructions to create my own atlastk server on an AWS Bitnami LAMP instance. 
 I followed all of the instructions in the server installation directions (https://atlastk.org/installation/server), including opening up port 53700.  I also have xdhq talking on 53710.  

When I launch the Python version of AtlasTK using the Q37 server, everything runs fine.  When I add the environmental variables to point to my server, it connects, opens up a new window in my browser, but then immediately displays the message "You are disconnected from the backend (exit message #3)!"  I also get an error in my LAMP instance: 

(23/12/2021 04:17:37) 203c5418-adf2-408a-802f-b292aad6b58a 3.210.50.26: PYH
{ 23/12/2021 04:17:40 GNR error : faaspool.cpp(648) }

Any idea where I might be going wrong?

Versions: XDHWebQ V20211208 (http://q37.info/tools/xdhwebq/)
Atlastk for PYthon version 0.13

Thanks!

**Comment by epeios-q37** [comment]
Could you show what is displayed in the console from which you launch your Python application, for both cases, when you connect to the default Q37 server, and also when you connect to your server?

Thanks!

**Comment by bkcallihan** [comment]
Here is what is displayed in the console in both cases:
-----
With Q37 server
-----
Connection to 'faas.q37.info:53700'...
Connected to 'faas.q37.info:53700'.

****************************************************************************
     Your application is connected to the free public server. Welcome!
     THIS SERVICE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
     EXPRESS OR IMPLIED. THE USE OF THIS SERVICE IS AT YOUR OWN RISK.
****************************************************************************
					
http://faas.q37.info/xdh.php?_token=94e98573-6a42-45c7-b7e9-7eecbcf9ec40
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Open above URL in a web browser (click, right click or copy/paste). Enjoy!

Opening in existing browser session.
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
<note - libva issue is known - it is because I am running from a VM>

----------
With my own server
----------

Environmental Variables:
ATK_PADDR=faas.chesterweb.us
ATK_PPORT=53700
ATK_WADDR=faas.chesterweb.us

Python version 3.7

Output from Python Console:

Connection to 'faas.chesterweb.us:53700'...
Connected to 'faas.chesterweb.us:53700'.

****************************************************************************
     Your application is connected to the free public server. Welcome!
     THIS SERVICE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
     EXPRESS OR IMPLIED. THE USE OF THIS SERVICE IS AT YOUR OWN RISK.
****************************************************************************
                         
http://faas.chesterweb.us/xdh.php?_token=8e9c206f-02b4-4ac5-903c-955427f636ec
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Open above URL in a web browser (click, right click or copy/paste). Enjoy!

Opening in existing browser session.
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
<note - libva issue is known - it is because I am running from a VM>

Message in Chrome Browser (same happened in Firefox):
You are disconnected from the backend (exit message #3)!
Reload

Message from server terminal:
12:53:40) (N/A) 127.0.0.1: Dump (1)
{ 23/12/2021 12:54:06 GNR error : faaspool.cpp(648) }

**Comment by epeios-q37** [comment]
Please launch your Python application with the environment variables set so it connects to your server, plus the environment variable `ATK` set to `none` (this will prevent the automatic launching of the web browser), and look if the `GNR error : faaspool.cpp(648)` message appears in the server terminal as soon as you launched your Python application.
If not, open then the displayed URL (`http://faas.chesterweb.us/xdh.php?_token=…`), and look if the `GNR error : faaspool.cpp(648)` appears then in the server terminal.
Please provide also all the messages displayed in the terminal server during this test.

**Comment by epeios-q37** [comment]
Please provide the content of the configuration file of your web server (Apache, I presume).

**Comment by bkcallihan** [comment]
vhosts file:
----
<VirtualHost *:80>
  DocumentRoot "/var/www/faas"
  ServerName faas.chesterweb.us
  ProxyPass "/xdh/" "ws://localhost:53700/"
</VirtualHost>

Key parts of httpd.conf
----
<Directory "/var/www/faas/">
   Options Indexes FollowSymLinks
   AllowOverride None
   Require all granted
</Directory>

Let me know if you need more.

**Comment by epeios-q37** [comment]
Got it!
It's (last line of the vhosts file) `ProxyPass "/xdh/" "ws://localhost:53710`, not `ProxyPass "/xdh/" "ws://localhost:53700` (`53710` instead of `53700`).

**Comment by bkcallihan** [comment]
Perfect.  Thank you so much for the help!  I did mix up the 53700 and 53710!  

Thank you for this great software - it is very useful and makes quick work for Python-based web-app demos!

**Comment by epeios-q37** [comment]
Glad you find it useful.

By the way, you wrote that you set following environment variables:

```
ATK_PADDR=faas.chesterweb.us
ATK_PPORT=53700
ATK_WADDR=faas.chesterweb.us
```

`ATK_PADDR=faas.chesterweb.us` should suffice, as the default value for `ATK_PPORT` is `53700`, and, when not specifically set, `ATK_WADDR` takes the same value as `ATK_PADDR`.
