### ISSUE TITLE
Clarification on ConnectionTimeout

### ISSUE THREAD

**Issue by bkcallihan** [epeios-q37/xdhq#2]
I have successfully been running my own XDHQXDH server to run my AtlasTK scripts.  However, I am wanting to change the server timeout.  Currently, I still lose the backend connection every 90 seconds (although it comes back fine when I hit reload).  I did modify the xdhqxdh.xcfg file, and changed <ConnectionTimeout> to 360 instead of 90.  However, I don't see a change, even after rebooting the server.

My xdhqxdh file looks like the following:

<?xml version="1.0" encoding="UTF-8"?>
<Configurations xmlns:xpp="http://q37.info/ns/xpp/">
 <Configuration target="xdhqxdh">
  <Parameters>
   <Language>en</Language>
   <Command>Test</Command>
   <FaaS>
    <Service>53700</Service>
    <ConnectionTimeout>360</ConnectionTimeout>
   </FaaS>
   <Plugins/>
  </Parameters>
  <Definitions>
...

Any hints on what I might be doing wrong?

Thanks!

**Comment by epeios-q37** [comment]
This is probably due to the WebSocket timeout of your web server.

The timeout in the `xdhqxdh.xcfg` are in minutes and is for the *backend*.

**Comment by bkcallihan** [comment]
Found it - thanks!
